services:
  sonarr:
    volumes:
      - ${DATA_ROOT}/qbittorrent/media:/data/media
      - ${DATA_ROOT}/qbittorrent/torrents/tv:/data/torrents/tv
      - ${NAS_MEDIA_ROOT}/tv:/data/nas/tv

  radarr:
    volumes:
      - ${DATA_ROOT}/qbittorrent/media/:/data/media/
      - ${DATA_ROOT}/qbittorrent/torrents/movies:/data/torrents/movies
      - ${NAS_MEDIA_ROOT}/movies:/data/nas/movies

        # vpn:
        #   image: ghcr.io/qdm12/gluetun
        #   container_name: gluetun
        #   cap_add:
        #     - NET_ADMIN
        #   devices:
        #     - /dev/net/tun:/dev/net/tun
        #       #    ports:
        #     #      # qbittorrent ports
        #     #      - 8080:8080
        #     #      - 6881:6881
        #     #      - 6881:6881/udp
        #     #    #  # origw
        #   #  - 8888:8888/tcp # HTTP proxy
        #   #  - 8388:8388/tcp # Shadowsocks
        #   #  - 8388:8388/udp # Shadowsocks
        #   volumes:
        #     - ${CONFIG_ROOT}:/gluetun
        #   environment:
        #     # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
        #     - VPN_SERVICE_PROVIDER=surfshark
        #     - VPN_TYPE=wireguard
        #     # OpenVPN:
        #     #- OPENVPN_USER=
        #     #- OPENVPN_PASSWORD=
        #     # Wireguard:
        #     # - WIREGUARD_PRIVATE_KEY=[private_key_from_surfshark_portal]
        #     # - WIREGUARD_ADDRESSES=[ip_range_from_surfshark_portal]
        #     - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
        #     - WIREGUARD_ADDRESSES=10.64.222.21/32
        #     # Timezone for accurate log times
        #     - TZ=${TIMEZONE}
        #     # Server list updater
        #     # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
        #     - UPDATER_PERIOD=
        #     - SERVER_COUNTRIES=Italy,Germany,Netherlandn
        #   healthcheck:
        #     test: ping -c 1 www.google.com || exit 1
        #     interval: 30s
        #     timeout: 10s
        #     retries: 3
        #   restart: always

